### ISSUE TITLE
Doesn't work with apps with auth

### ISSUE THREAD

**Issue by cindro** [anuraj/HtmlMinificationMiddleware#1]
This is a great middleware and it works.

But it stops apps with authentication from working, if an app has app.UseCookieAuthentication the login will fail.

Any ideas?

**Comment by cindro** [comment]
The updates didn't fix the problem.

**Comment by anuraj** [comment]
I have added on example with cookie authentication. Can you try now?

**Comment by cindro** [comment]
Yesss, it works beautifully. This is without a doubt the best, simpliest and lightest HTML Minifier out there, thank you so much Anuraj.
