### ISSUE TITLE
Opting out from minification

### ISSUE THREAD

**Issue by cindro** [anuraj/HtmlMinificationMiddleware#2]
Once app.UseHTMLMinification() is added to the start.cs file it applies on the whole app.

Now, is there a way for some Controller Actions to opt out from Minification?

I have an Action result that converts HTML code to PDF file and it has now stopped working.

**Comment by anuraj** [comment]
#2 - Fixed.

**Comment by cindro** [comment]
Works like a charm, thank you a million for this great plugin.
