### ISSUE TITLE
Multiple pages opting out from minification

### ISSUE THREAD

**Issue by cindro** [anuraj/HtmlMinificationMiddleware#3]
I love this package and it works perfectly.

I am trying to opt out from the minification on multiple pages that generate pdf files, does this package support for multiple opt out? I can only do 1 page now as seen below.

app.UseHTMLMinification("(w_)print1_");

**Comment by cindro** [comment]
@anuraj, excited about Build 1.0.7

**Comment by anuraj** [comment]
You can try this option right?

`app.UseHTMLMinification("(w*)Page*");`

**Comment by anuraj** [comment]
Closing it assuming the problem got solved.
