### ISSUE TITLE
ASP.NET Core 1.0 Upgrade?

### ISSUE THREAD

**Issue by cindro** [anuraj/HtmlMinificationMiddleware#4]
Any plans for Core 1.0 upgrade? such a lovely little library.

**Comment by cindro** [comment]
I did download it and changed its dependencies from AspNet to AspNetCore and it worked, but the library is suddenly buggy and only works after multiple refreshes and doesn't work on every page load.

Does it have anything to do with the WebHostBuilder?

**Comment by anuraj** [comment]
Yes I am planning to do an update. Related to your question, I did the modification (from RC / Beta code to Core RTM) and it is working without any issue.

**Comment by cindro** [comment]
@anuraj after many quick refreshes it breaks, try doing fast multiple refreshes while using HtmlMinificationMiddleware on Core RTM.

I just try it again and same thing happened.

When testing, make sure you have app.UseMvc as well and see what happens. #4

**Comment by anuraj** [comment]
@cindro It is fixed now. You can take the source code and build, I am yet to fix the build and nuget package. Sorry for the delay :(

**Comment by anuraj** [comment]
Nuget package also updated. Use 2.0.1 version which supports middleware support as well.

**Comment by cindro** [comment]
Is it possible for you to release a new version targeting netcoreapp3.1?

`<PropertyGroup>`
`      ` `<TargetFramework>netcoreapp3.1</TargetFramework>`
`</PropertyGroup>`
`<ItemGroup>`
`      ` `<FrameworkReference Include="Microsoft.AspNetCore.App" />`
`</ItemGroup>`
