### ISSUE TITLE
Exception problems

### ISSUE THREAD

**Issue by cindro** [anuraj/HtmlMinificationMiddleware#5]
@anuraj, I am using ASP.NET Core (.NET Core 2.0 Preview 2)

This great middleware won't work with app.UseExceptionHandler("/error"); app.UseStatusCodePages();

app.UseHTMLMinification("(w*)page*");

**Comment by cindro** [comment]
Strangely enough, it works when I call this middleware before app.UseStatusCodePages().

Below order works:

app.UseExceptionHandler("/error");
app.UseHTMLMinification("(w*)page*");
app.UseStatusCodePages();

And on publishing this middleware must come after app.UseStaticFiles() for images to appear.

**Comment by anuraj** [comment]
Sorry for the late response. Since StatusCodePagesMiddleware handles the status codes, may be the minification middleware unable to get the status code. And stops working. 

As it is working by moving before StatusCodePagesMiddleware, I am closing this issue.

**Comment by cindro** [comment]
Fair enough.
